name: Server-Dependencies

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_run:
    workflows: [Web]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Success-Check:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # Runs a single command using the runners shell
    - name: Send confirmation of connection
      run: echo "doing the dependencies stuff"
  Fail-Check:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    # Runs a single command using the runners shell
    - name: Send confirmation of connection
      run: echo "part 2 failure (never happens)"
  
