# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Ooooauuuugh:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    env:
      WORKFLOW_NAME: ${{ toJson(github.workflow) }}
      RUN_NUMBER: ${{ toJson(github.run_number) }}
      RUN_ATTEMPT: ${{ toJson(github.run_attempt) }}
    steps:
    # Runs a single command using the runners shell
    - name: Run a brief command
      run: |
        echo "Running $WORKFLOW_NAME"
        echo "Build Number $RUN_NUMBER"
        echo "Run Attempt(s): #RUN_ATTEMPT"
