name: Server-Dependencies

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_run:
    workflows: [Server]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Success-Check:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # Runs a single command using the runners shell
    - name: Send confirmation of connection
      run: echo "previous workflow succeed"
  Prebuild-Fail:
    # The type of runner that the job will run on
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    # Runs a single command using the runners shell
    - name: Send confirmation of connection
      run: echo "part 2 failure"
  Prebuild-Success:
    runs-on: windows-latest
    needs: Success-Check
    steps:
    - name: testing the needs attribute
      run: echo "augh"
  
