name: Server

on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]

jobs:
  Pre-Build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    outputs:
      output1: "frog"
      output2: "even cooler frog"
    env:
      WORKFLOW_NAME: ${{ github.workflow }}
      RUN_NUMBER: ${{ github.run_number }}
      RUN_ATTEMPT: ${{ github.run_attempt }}
    steps:
    # Runs a single command using the runners shell
    - name: Run a brief command
      shell: pwsh
      run: |
        Write-Output "Running $env:WORKFLOW_NAME"
        Write-Output "Build Number $env:RUN_NUMBER"
        Write-Output "Run Attempt(s): $env:RUN_ATTEMPT"
    - name: Next part of prebuild
      run: Write-Output "ooh it's prebuilding!"
      
  Build:
    runs-on: windows-latest
    needs: Pre-Build
    steps:
      - name: testing outputs
        env:
          OUTPUT1: ${{ needs.Pre-Build.outputs.output1 }}
          OUTPUT2: ${{ needs.Pre-Build.outputs.output2 }}
        run: Write-Output are you interested in a $env:OUTPUT1? or perhaps, an $env:OUTPUT2?
